version: 0.2
phases:
 install:
   commands:
     - echo "install step"
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - echo "build step"
 post_build:
   commands:
     - echo "post_build step"
artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    googlesheet_url_js:
     babase-directory: $CODEBUILD_SRC_DIR
     files:
      - '**/*'
