version: 0.2
phases:
 install:
   commands:
     - echo "install step"
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - echo "build step"
 post_build:
   commands:
     - echo "post_build step"
artifacts:
  files:
    - '**/*.html'
    - '**/*.ico'
    - '**/*.css'
    - 'scripts/*'
    - '**/*.png'
    - '**/*.geojson'
    - 'scripts/Leaflet.awesome-markers/dist/*'
    - 'scripts/leaflet-providers/*'
