var constants = {
  // Tabs in Google Sheet
  notesSheetName: 'Notes',
	optionsSheetName: 'Options',
	pointsSheetName: 'Points',
  polygonsSheetName: 'Polygons',
  polylinesSheetName: 'Polylines',
  /* OPTIONS */
	// Map Info
  _mapTitle: 'Map Title',
  _mapSubtitle: 'Map Subtitle',
  _mapTitleDisplay: 'Display Title',
	_authorName: 'Author Name',
	_authorURL: 'Author Email or Website',
  _codeCredit: 'Author Code Credit',
	_githubRepo: 'Author Code Repo',
	// Map Settings
	_tileProvider: 'Basemap Tiles',
	_markercluster: 'Cluster Markers',
  _introPopupText: 'Intro Popup Text',
  _initZoom: 'Initial Zoom',
  _initLat: 'Initial Center Latitude',
  _initLon: 'Initial Center Longitude',
	// Map Controls
	_mapSearch: 'Search Button',
  _mapSearchKey: 'Mapzen Search Key',
	_mapSearchCircleRadius: 'Search Radius',
	_mapSearchZoom: 'Search Results Zoom Level',
	_mapZoom: 'Zoom Controls',
	_mapMyLocation: 'Show My Location',
	_mapAttribution: 'Credits and Attribution',
	// Point Map Display
	_pointsLegendTitle: 'Point Legend Title',
	_pointsLegendPos: 'Point Legend Position',
  _pointsLegendIcon: 'Point Legend Icon',
  // Table Map
  _displayTable: 'Display Table',
  _tableHeight: 'Table Height',
  _tableColumns: 'Table Columns',
  _tableHeaderColor: 'Table Header Color',
  // Polyline Map Controls
  _polylinesLegendTitle: 'Polyline Legend Title',
  _polylinesLegendPos: 'Polyline Legend Position',
  _polylinesLegendIcon: 'Polyline Legend Icon',
  _polylinesWeight: 'Polyline Thickness',
	// Polygon Map Display
	_polygonsLegendTitle: 'Polygon Legend Title',
	_polygonsLegendPosition: 'Polygon Legend Position',
  _polygonsLegendIcon: 'Polygon Legend Icon',
  _polygonsGeojsonURL: 'Polygon GeoJSON URL',
  _popupProp: 'Property Popups, Labels',
  _polygonLayers: 'Polygon Properties, Labels',
  _bucketDivisors: 'Property Ranges',
	_colorScheme: 'Property Range Color Palette',
  _colorOpacity: 'Polygon Color Opacity',
  _outlineColor: 'Polygon Outline Color',
  _bucketColors: 'Property Range Manual Colors',
  _polygonDisplayImages: 'Show Images When Available',
  _polygonLabel: 'Show Polygon Labels',
  _polygonLabelZoomLevel: 'Show Polygon Labels at Zoom Level',
  _polygonShowOnStart: 'Show Polygon Data on Start',
};
