var constants = {
  // Tabs
	informationSheetName: 'Options',
	pointsSheetName: 'Points',
  polygonsSheetName: 'Polygons',
  // Columns
  polygonsProp: 'Property',
  polygonsPropName: 'Property Alias',
  // Options
  _pageTitle: 'Webpage Title:',
  _displayTitle: 'Display Title on the Map:',
  _infoPopupText: 'Info Popup Text:',
  _initZoom: 'Initial Zoom:',
  _initLat: 'Initial Center Latitude:',
  _initLon: 'Initial Center Longitude:',
  _markercluster: 'Markercluster:',
  _tileProvider: 'Tile Provider:',
  _authorName: 'Author Name:',
  _authorURL: 'Author Email or Website:',
  _githubRepo: 'Author GitHub Repo Link:',
  _pointsTitle: 'Layers Box Title:',
  _attrPos: 'Map Attribution Position:',
  _layersPos: 'Map Layers Control Position:',
  _zoomPos: 'Map Zoom Control Position:',
  _geojsonURL: 'GeoJSON URL:',
  _bucketProp: 'Properties to Display:',
  _bucketPropName: 'Property Aliases:',
  _bucketDivisors: 'Bucket Divisors:',
  _bucketColors: 'Bucket Colors:',
  _legendTitle: 'Legend Title:',
  _legendPosition: 'Map Polygons Legend Position:',
  _mapSearch: 'Map Search On/Off:',
  _mapSearchPos: 'Map Search Control Position:',
  _searchCircleRadius: 'Search Circle Radius:',
  _searchZoom: 'Search Preferred Zoom:',
  _searchBounds: 'Search Bounds:',
  _colorScheme: 'Use ColorBrewer Palette:',
  _polygonDisplayImages: 'Display Images When Available:',
  _locateControlPos: 'Locate Control Position:',
};
