var constants = {
  // Tabs in Google Sheet
  notesSheetName: 'Notes',
	optionsSheetName: 'Options',
	pointsSheetName: 'Points',
  polygonsSheetName: 'Polygons',
  polylinesSheetName: 'Polylines',
  /* OPTIONS */
	// Map Info
  _pageTitle: 'Page Title',
  _pageSubtitle: 'Subtitle',
  _displayTitle: 'Display Title',
	_authorName: 'Author Name',
	_authorURL: 'Author Email or Website',
  _codeCredit: 'Code Credit',
	_githubRepo: 'Author GitHub Repo Link',
	// Map Settings
	_tileProvider: 'Basemap Tiles',
	_markercluster: 'Markercluster',
  _introPopupText: 'Intro Popup Text',
  _initZoom: 'Initial Zoom',
  _initLat: 'Initial Center Latitude',
  _initLon: 'Initial Center Longitude',
	// Map Controls
	_displayMapSearch: 'Search Button Display',
  _mapzenKey: 'Mapzen Search Key',
	_mapSearchPos: 'Search Button Position',
	_searchCircleRadius: 'Search Radius',
	_searchZoom: 'Search Results Zoom Level',
	_searchBounds: 'Search Area Boundaries',
	_zoomPos: 'Zoom Controls',
	_locateControlPos: 'Show My Location',
	_attrPos: 'Credits and Attribution',
	// Point Map Display
	_pointsLegendTitle: 'Point Legend Title',
	_pointsLegendPos: 'Point Legend Position',
  // Polyline Map Controls
  _polylinesLegendTitle: 'Polyline Legend Title',
  _polylinesLegendPos: 'Polyline Legend Position',
  _polylinesWeight: 'Polyline Thickness',
	// Polygon Map Display
	_polygonsLegendTitle: 'Polygon Legend Title',
	_polygonsLegendPosition: 'Polygon Legend Position',
  _polygonsGeojsonURL: 'Polygon GeoJSON URL',
  _popupProp: 'Property Popups, Labels',
  _polygonLayers: 'Polygon Properties, Labels',
  _bucketDivisors: 'Property Ranges',
	_colorScheme: 'Property Range Color Palette',
  _colorOpacity: 'Polygon Color Opacity',
  _outlineColor: 'Polygon Outline Color',
  _bucketColors: 'Property Range Manual Colors',
  _polygonDisplayImages: 'Display Images When Available',
  _polygonLabel: 'Display Polygon Labels at Zoom Level',
  _polygonLabelMaxZoom: 'Maximum Zoom for Polygon Label',
};
